### ISSUE TITLE
Watch and comment section for desktop

### ISSUE THREAD

**Issue by devbobnwaka** [zuri-training/COL_FILMS_TEAM_115#14]

**Comment by Favour-sama** [comment]
Done

**Comment by Favour-sama** [comment]
**Watch and comment section** - https://www.figma.com/file/1Lbby6nGRPwmBfwh9Yp6SS/col_films?node-id=1155%3A2340

**Watch view Expanded** - https://www.figma.com/file/1Lbby6nGRPwmBfwh9Yp6SS/col_films?node-id=1155%3A2139

**Watch view Default** - https://www.figma.com/file/1Lbby6nGRPwmBfwh9Yp6SS/col_films?node-id=1155%3A2117

**Watch view Next Movie** - https://www.figma.com/file/1Lbby6nGRPwmBfwh9Yp6SS/col_films?node-id=1155%3A2091

**Watch view Subtitle** - https://www.figma.com/file/1Lbby6nGRPwmBfwh9Yp6SS/col_films?node-id=1155%3A2068

**Watch view Subtitle options** - https://www.figma.com/file/1Lbby6nGRPwmBfwh9Yp6SS/col_films?node-id=1155%3A2043

**Watch view Playback speed** - https://www.figma.com/file/1Lbby6nGRPwmBfwh9Yp6SS/col_films?node-id=1155%3A2022

**Watch view Playback speed options** - https://www.figma.com/file/1Lbby6nGRPwmBfwh9Yp6SS/col_films?node-id=1155%3A1979

**Watch view Expand** - https://www.figma.com/file/1Lbby6nGRPwmBfwh9Yp6SS/col_films?node-id=1155%3A1958
